version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: reading-tracker-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_DATABASE: "reading_tracker"
      TZ: "UTC"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci