spring:
  application:
    name: reading-tracker
  profiles:
    active: dev #기본 프로파일 활성화 : 개발 환경
  
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 0
    repair-on-migrate: true
    validate-on-migrate: false  # 체크섬 불일치 시 임시로 비활성화 (repair 후 다시 true로 변경)

server:
  port: 8080

sharedsync:
  websocket:
    endpoint: "/ws-sharedsync"
    allowed-origins:
      - "http://localhost:5173"
      - "http://localhost:3000"
      - "http://127.0.0.1:8000"

data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

auth:
  enabled: true

presence:
  enabled: true